### ISSUE TITLE
Error: No workspace

### ISSUE THREAD

**Issue by xiaozai512** [mesosphere/dcos-jenkins-service#123]
Environment version：
       DCOS 1.8
       mesosphere/dcos-jenkins-service  Version 2.1.0-2.19.3
Click Build Now
      Bugs wrong： (pending—Waiting for next available executor)  

Click on the workspace

Dec 27, 2016 11:27:08 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Nodes went offline. Hence fetching it through master
Dec 27, 2016 11:27:08 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Workspace Path: jenkins/workspace/tenbent-merchant-center
Dec 27, 2016 11:27:08 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Workspace exists ? false
Dec 27, 2016 11:27:10 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Nodes went offline. Hence fetching it through master
Dec 27, 2016 11:27:10 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Workspace Path: jenkins/workspace/tenbent-merchant-center
Dec 27, 2016 11:27:10 AM org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Workspace exists ? false

All by default configuration generated war package build image, it is strange to report such a mistake. Please come across or know the problem to help solve this problem. On the way to try to build their own bottom image, replace the jenkins version, failed to solve. . .

**Comment by ssk2** [comment]
@xiaozai512: this is normal behaviour with the Jenkins plugin. It's waiting for a Mesos resource offer so that it can spin up a new Jenkins build agent. Does it stay like this indefinitely? If so, you may need to check the available resources in your DC/OS cluster - how many private agents do you have? You need to have enough spare resources available to launch at least one Mesos agent (specified under the "Cloud" configuration, underneath "Mesos Cloud').

**Comment by xiaozai512** [comment]
@ssk2 ：Thank you! According to your answer I find the problem, and now can run out of the results! Thank you! The next step is to start looking at how the build image will be built into the DC / OS, DC / OS is too strong it!Still learning...

**Comment by ssk2** [comment]
Glad to hear that! I'm closing this issue for now - please let us know if you have any other questions.
