### ISSUE TITLE
Jenkins new version available 2.32.1

### ISSUE THREAD

**Issue by liuggio** [mesosphere/dcos-jenkins-service#125]
Hi,
would be awesome to have the new Jenkins version, it's a **LTS**

**Comment by ssk2** [comment]
Hi @liuggio, will update this once #122 lands.

**Comment by LinkMJB** [comment]
Just a warning/heads-up, I manually upgraded Jenkins on DC/OS to 2.32.1 using my own Dockerfile and ran into compatibility issues between the Mesos plugin and the version of Mesos bundled with DC/OS 1.7-open. The Jenkins Mesos plugin >= 0.14.0 is not backward compatible with Mesos <= 1.0, and the Jenkins Mesos plugin <= 0.14.0 is not compatible with Jenkins >= 2.32.1. You will want to make sure you upgrade DC/OS to 1.8 prior to upgrading, if you have not already.

**Comment by ssk2** [comment]
Ah, thanks for pointing that out. We will make sure the package which contains the updated plugin mandates a minimum of DC/OS 1.8.

**Comment by colin-msphere** [comment]
Thank you for the issue. This has been addressed in PR #122.

**Comment by colin-msphere** [comment]
The latest release should resolve this issue. Please let me know if you are still seeing these errors.
