### ISSUE TITLE
Jenkins fail to start due to GLib-GIO-ERROR

### ISSUE THREAD

**Issue by descrepes** [mesosphere/dcos-jenkins-service#126]
Hi,

After installing some plugins (like Rundeck), Jenkins fail to restart with the following error:
`GLib-GIO-ERROR**: No GSettings schemas are installed on the system`

To workaround this issue, please add the package 'gsettings-desktop-schemas' in the Dockerfile.

Regards

**Comment by ssk2** [comment]
Thanks, we will try to address this with #122.

**Comment by ssk2** [comment]
Hi @descrepes: hopefully this has now been solved. If not, please raise an issue [in JIRA]( https://jira.mesosphere.com/secure/CreateIssueDetails!init.jspa?pid=14110&issuetype=3).
