### ISSUE TITLE
Accept nginx proxy over-rides through DC/OS variables

### ISSUE THREAD

**Issue by LinkMJB** [mesosphere/dcos-jenkins-service#127]
For example:

  proxy_connect_timeout       600;
  proxy_send_timeout          600;
  proxy_read_timeout          600;
  send_timeout                600;

see: https://www.scalescale.com/tips/nginx/504-gateway-time-out-using-nginx/#
see: http://nginx.org/en/docs/http/ngx_http_proxy_module.html

**Comment by ssk2** [comment]
[Moved to JIRA](https://jira.mesosphere.com/browse/JENKINS-139).
