### ISSUE TITLE
git version too outdated

### ISSUE THREAD

**Issue by interone-ms** [mesosphere/dcos-jenkins-service#128]
Hi,

the package is based on Debian stable, which carries git 2.1.4.

The problem is that this ancient git from 2014 does not understand the syntax for non-standard SSH ports: `[git@git.company.tld:31337]:user/repo.git` will throw an error, as ssh tries to connect to the host "git.company.tld:31337" which fails. The cause is a bad invocation in the old git - instead of `ssh git@git.company.tld -p 31337` it calls `ssh git@git.company.tld:31337`.

The fix is to wget and install these two packages in the Dockerfile during the image build:

- http://ftp.de.debian.org/debian/pool/main/g/git/git-man_2.11.0-2_all.deb
- http://ftp.de.debian.org/debian/pool/main/g/git/git_2.11.0-2_amd64.deb

Also, the plugins in the image should be updated, when freshly deploying the image using Universe there's a boatload of outdated plugins and Jenkins itself.

**Comment by colin-msphere** [comment]
@interone-ms - has this been resolved with the latest release?
