### ISSUE TITLE
Support for Cloudbee Enterprise Jenkins

### ISSUE THREAD

**Issue by PandaXass** [mesosphere/dcos-jenkins-service#142]
Hi,

As a Jenkins Enterprise user, it will be great that we can have Jenkins Enterprise Universe package available as well.

**Comment by ssk2** [comment]
Hi @PandaXass: noted, thanks! I suggest raising this with your CloudBees account executive :).

**Comment by PandaXass** [comment]
Hi @ssk2: thanks for the quick reply! I will try to raise another one with the license settings if I can figure that out ;p
